### ISSUE TITLE
Method host_numbers in fritzhosts.py always returns 16

### ISSUE THREAD

**Issue by caiuspb** [deisi/fritzconnection#1]
Hi,
like you already noticed the method host_numbers in fritzhosts.py always returns 16.
I investigated the code and it is indeed a fritzbox API error.

So there are three possibilities 
1. Check if there are other ways to check the number of hosts within the official API
2. Substitute the for loop with a 'while True' loop and query the fritzbox and break as soon as we receive an empty message
3. Parse the raw HTML page (may not work on every model)

Option 2 would be a good workaround but option 1 would be the best

**Comment by deisi** [comment]
Hi,

About this matter, I already asked the guy who wrote fritzconnection, 
and he responded, that this is a problem of the frizbox, and there is 
currently no way to get the correct number of hosts. One simply has to 
wait and hope that an update from AVM solves this. (I don't have IOS6 
maybe this new one solves it. I can not test, since I don't have a 
supported box.)

Suggestion 2. should be easy to implement.

Suggestion 3. I have no Idear. Sound possible but like a lot of work and 
cumbersome.
